version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
      docker: latest
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd calculate-networth
      - mvn compile
      - mvn clean package -Dmaven.test.skip=true
      - echo "building docker image"
      - docker build -t cde20calculate-networth-service:latest .
      - docker tag cde20calculate-networth-service:latest 234825976347.dkr.ecr.us-east-2.amazonaws.com/cde20calculate-networth-service:latest
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 234825976347.dkr.ecr.us-east-2.amazonaws.com/cde20calculate-networth-service:latest
    - printf '[{"name":"cde20ij012pod4networth-container","imageUri":"%s"}]' 234825976347.dkr.ecr.us-east-2.amazonaws.com/cde20calculate-networth-service:latest > taskdefinition.json
artifacts:
  files:
    - calculate-networth/taskdefinition.json