version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
      docker: latest
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd daily-mutualfund
      - mvn compile
      - mvn clean package -Dmaven.test.skip=true
      - echo "building docker image"
      - docker build -t daily-mutualfund:latest .
      - docker tag daily-mutualfund:latest 234825976347.dkr.ecr.us-east-2.amazonaws.com/daily-mutualfund:latest
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 234825976347.dkr.ecr.us-east-2.amazonaws.com/daily-mutualfund:latest
    - printf '[{"name":"cde20ij012pod4mutualfund-container","imageUri":"%s"}]' 234825976347.dkr.ecr.us-east-2.amazonaws.com/daily-mutualfund:latest > taskdefinition.json
artifacts:
  files:
    - daily-mutualfund/taskdefinition.json